### ISSUE TITLE
Server fails to run on NixOS Linux

### ISSUE THREAD

**Issue by srid** [Zaid-Ajaj/SAFE.React#12]
Again, on NixOS:

```
❯ dotnet run
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Possible cause seen from `strace` output:

```
8369  execve("/home/srid/code/Baseline/server/bin/Debug/netcoreapp3.1/Server", ["/home/srid/code/Baseline/server/"...], 0x563eee81d4b0 /* 133 vars */) = -1 ENOENT (No such file or directory)
```

This binary exists, but it is not linked properly to `libstdc++.so.6`

```
❯ ldd bin/Debug/netcoreapp3.1/Server
        linux-vdso.so.1 (0x00007ffe741f5000)
        libpthread.so.0 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libpthread.so.0 (0x00007eff59fb7000)
        libdl.so.2 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libdl.so.2 (0x00007eff59fb2000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libm.so.6 (0x00007eff59e6f000)
        libgcc_s.so.1 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libgcc_s.so.1 (0x00007eff59e55000)
        libc.so.6 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libc.so.6 (0x00007eff59c92000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib64/ld-linux-x86-64.so.2 (0x00007eff59fda000)
```

To resolve this, I had to set LD_LIBRARY_PATH [the Nix-way](https://discourse.nixos.org/t/what-is-the-nix-way-to-specify-ld-library-path/6407/4?u=srid),

```
export LD_LIBRARY_PATH=$(nix eval --raw nixpkgs.stdenv.cc.cc.lib)/lib:$LD_LIBRARY_PATH
```

After doing this, `ldd` can resolve `libstdc++.so.6` - but the binary still doesn't run.

```
❯ bin/Debug/netcoreapp3.1/Server
bash: bin/Debug/netcoreapp3.1/Server: No such file or directory
```

(Note: ldd on this binary resolves all dependencies).

Not sure what the problem here is. I'll go back to Windows for now, but leaving this here as a record of my attempts.

**Comment by Zaid-Ajaj** [comment]
Can you please tell me more about the problem? 
 - What is your dotnet version exactly? i.e. `dotnet --version` 
 - In which directory are you running `dotnet run`

**Comment by srid** [comment]
dotnet `5.0.100`, and I'm running it from `./server` as the README asks me to.

---

Wonder what this "interpreter" thing is ... it refers to a path that doesn't exist.
```
❯ file ./bin/Debug/netcoreapp3.1/Server
./bin/Debug/netcoreapp3.1/Server: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cc4d564ae32adf40ceadffc087e0ea680db4cc95, stripped

❯ file /lib64/ld-linux-x86-64.so.2
/lib64/ld-linux-x86-64.so.2: cannot open `/lib64/ld-linux-x86-64.so.2' (No such file or directory)
```

**Comment by Zaid-Ajaj** [comment]
Then your dotnet version looks good 🤔 to be honest I don't know much about NixOS so I am not sure why it isn't working for you. I test things with Ubuntu and there everything works without any changes for me

**Comment by srid** [comment]
Okay, I've temporarily resolved the issue using `--set-interpreter` from https://unix.stackexchange.com/questions/522822/different-methods-to-run-a-non-nixos-executable-on-nixos

Not an ideal solution obviously, as this needs automation in whatever build script we use. Generally on NixOS, we nixify the project - and I'm not prepared to do that just yet. 

---

I get a new error; I guess I have to force the template to use 5.0 now ...


```
❯ dotnet run
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/nix/store/ksmpymzshp0j8vaw6f457ry24xy9jfmw-dotnet-sdk-5.0.100/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=nixos.21.05pre275822.916ee862e87-x64
```

**Comment by Zaid-Ajaj** [comment]
> I get a new error; I guess I have to force the template to use 5.0 now ...

Inside the `.fsproj` files there is something called `<TargetFramework>netcoreapp3.1</Targetframework>` if you see this then change it to `<TargetFramework>net5.0</Targetframework>`

if you see `<TargetFramework>netstandard2.0</Targetframework>` then just keep it as is because it is compatible

**Comment by srid** [comment]
Okay, after changing dotnet version ...

```
❯ dotnet run
Configuration file config.json file was not found inside ./server
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: shell
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Saturn.Application.run(IHostBuilder app)
   at <StartupCode$Server>.$Program.main@() in /home/srid/code/Baseline/server/Program.fs:line 34
```

Okay, adding the following to server/config.json,

```json
{
  "DATABASE_CONNECTIONSTRING": "foo.db",
  "APP_NAME": "Baseline",
  "VERSION": "0.1.0-alpha"
}
```

But now:

```
❯ dotnet run
Found config.json file, loading variables
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: shell
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Saturn.Application.run(IHostBuilder app)
   at <StartupCode$Server>.$Program.main@() in /home/srid/code/Baseline/server/Program.fs:line 34
```

Not sure what that is about.

**Comment by srid** [comment]
Full diff, https://gist.github.com/srid/dd555e99d462b8ff6914de20f8807513

**Comment by Zaid-Ajaj** [comment]
This [piece of code](https://github.com/Zaid-Ajaj/SAFE.React/blob/master/server/Env.fs#L39-L53) runs on startup to gather your environment variables and makes them available throughout the code + includes _optional_ development time variables that you can add via config.json when you don't want to mess with your env vars. 

For some reason it is adding some variables twice even though I do check that the variables should only be added when not added before i.e. `if not (variables.ContainsKey(key)) then variables.Add(key, value)`

can you simplify it to just
```fs
/// Returns enviroment variables as a dictionary
let environmentVars() =
    let variables = Dictionary<string, string>()
    let userVariables = Environment.GetEnvironmentVariables(EnvironmentVariableTarget.User)
    for pair in userVariables do
        let variable = unbox<Collections.DictionaryEntry> pair
        let key = unbox<string> variable.Key
        let value = unbox<string> variable.Value
        if not (variables.ContainsKey(key)) && key <> "PATH" then variables.Add(key, value)
    variables
```
and see what happens (i.e. without the process variables)

**Comment by srid** [comment]
Great; with that change, the server is now running:

```
❯ dotnet run
Found config.json file, loading variables
[19:25:30 INF] Now listening on: https://localhost:6001
[19:25:30 INF] Now listening on: http://localhost:6000
[19:25:30 INF] Application started. Press Ctrl+C to shut down.
[19:25:30 INF] Hosting environment: Development
[19:25:30 INF] Content root path: /home/srid/code/Baseline/server
```

By the way, why is it listening on *two* ports?

**Comment by srid** [comment]
FWIW, the reason I had to change the ports is to do with [IPFS](https://ipfs.io/) arrogating the ports 8080 and 5001.

**Comment by Zaid-Ajaj** [comment]
> By the way, why is it listening on two ports?

It's a dotnet thing, one for http and another for https. I think you can change that via the `--urls` variable or maybe it was `--application-urls` I am not sure tbh

**Comment by srid** [comment]
Alright, since this works (looks like frontend is not using backend at all in the template), I'll close this. Thanks!

**Comment by Zaid-Ajaj** [comment]
> looks like frontend is not using backend at all in the template

The frontend showcases a bunch of React components inside `./client/src/Components.fs` and inside `./client/src/Main.fs` is where the _root_ component is initialized. In this case it is the [Router()](https://github.com/Zaid-Ajaj/SAFE.React/blob/master/client/src/Components.fs#L84-L98) component
```fs
ReactDOM.render(
    Components.Router(),
    document.getElementById("feliz-app")
)
```
which routes to other components in the application when the URL changes. 

Navigate to `http://localhost:8080/#/server` to bring the `ServerCounter()` into view which will call the backend API and show data coming from there
