### ISSUE TITLE
Suggestion - make it clear how to interact with API

### ISSUE THREAD

**Issue by drk-mtr** [Zaid-Ajaj/SAFE.React#5]
Hi - thanks for sharing the template!

This is a suggestion rather than a bug.

It'd be good if there was a wired up example of client/server communication. I believe we need to use `Server.api.Counter` with useDeferred or similar, but I've played with various Fable templates over the last year and this wasn't obvious to me, so an example might make this easier for newcomers.

On the Fable.Remoting page the examples use Elmish, so it's hard to understand how that translates to this template.

**Comment by Zaid-Ajaj** [comment]
Hi @drk-mtr, that's a really good idea. I will some components that make use of `Server.api.Counter`

There are many ways to interact with the backend, the most basic ones are 
 - [Using Effects in Components](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/EffectfulComponents)
 - [Using Feliz.UseDeferred](https://zaid-ajaj.github.io/Feliz/#/Hooks/UseDeferred)
 - [Using Elmish via Feliz.UseElmish](https://zaid-ajaj.github.io/Feliz/#/Hooks/UseElmish) which allows you to use Elmish patterns as React components

**Comment by drk-mtr** [comment]
Fantastic - thanks.

As an aside, I love all the libraries you've created that make Fable easier to use - they solve so many of the problems I've come up against where I think "It would be really great if...". Massively appreciated :)

**Comment by Zaid-Ajaj** [comment]
Hi @drk-mtr I have added more components with examples in the default template that showcase calling backend code from the client :smile:

**Comment by drk-mtr** [comment]
Fantastic - thanks!
