### ISSUE TITLE
Type name case sensitivity - "Identifier has already been declared" compiler error

### ISSUE THREAD

**Issue by theimowski** [Zaid-Ajaj/SAFE.React#7]
This probably should go to Feliz issues, but it was easier for me to report it here as I had an example by hand.

When you have a `ReactComponent` defined in your source file like this one:

```fsharp
[<ReactComponent>]
let counter() = Html.div []
```

and then you define a `Counter` type above:

```fsharp
type Counter = { Dummy : unit }
```

then you end up with a compilation error even though you don't have any warnings / errors in editor:

```
ERROR in ./src/Components.fs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/theimowski/oss/SAFE.React/client/src/Components.fs.js: Identifier 'Counter' has already been declared (26:16)

  24 | }
  25 |
> 26 | export function Counter() {
```

I think the issue is that the Feliz Fable plugin renames `counter` to `Counter` to make React happy, but it collides with already existing type `Counter` defined above.

Not sure if you've encountered that, but if not I think this will hit a lot of users.

**Comment by Zaid-Ajaj** [comment]
Hi @theimowski, yeah I've encountered the problem and it is being tracked in [Feliz#286](https://github.com/Zaid-Ajaj/Feliz/issues/286) the solution will be probably be that Feliz will either emit warnings or fix the collision internally (could be difficult) but in any case, I am investigating the issues surrounding React tooling and will be fixing them soon. 

For now, please consider using an anonymous record or just a bunch of parameters till I get this sorted out 🙏

**Comment by theimowski** [comment]
sure no worries - thanks for quick answer!
